# SECTION 3: PANDAS (The Data Librarian)

## Load Data

In [7]:
import pandas as pd

df = pd.read_csv(r"E:\AI-ML\Day 3\data\data.csv")


### 1. Basic Data Inspection

In [4]:
 df.head() #Top 5 Rows

      Name  Age  Score
0    Alice   21     80
1      Bob   22     75
2  Charlie   23     90
3    David   24     85
4     Emma   20     88

In [5]:
df.tail() #Last 5 Rows

      Name  Age  Score
10   Kavya   22     89
11    Liam   23     91
12     Mia   20     84
13    Noah   25     73
14  Olivia   21     87

In [6]:
df.shape ## (rows, columns)

(15, 3)

In [10]:
df.columns #Show list of Columns Names

Index(['Name', 'Age', 'Score'], dtype='str')

In [9]:
df.dtypes #Show Data types of Columns

Name       str
Age      int64
Score    int64
dtype: object


### 2. Statistical Analysis

In [12]:
df['Score'].mean() #mean of Score

np.float64(82.86666666666666)

In [13]:
df['Score'].max() # Max of Score

np.int64(95)

In [14]:
df['Score'].min() #Minimum of Score

np.int64(70)

In [11]:
df.describe() #Shows Full Statistics

             Age      Score
count  15.000000  15.000000
mean   22.400000  82.866667
std     1.638815   7.347173
min    20.000000  70.000000
25%    21.000000  77.000000
50%    22.000000  84.000000
75%    23.500000  88.500000
max    25.000000  95.000000


### 3. Selecting Data

In [16]:
print(df[['Name', 'Score']])   # Multiple columns

       Name  Score
0     Alice     80
1       Bob     75
2   Charlie     90
3     David     85
4      Emma     88
5     Frank     70
6     Grace     95
7    Hannah     78
8    Ishaan     82
9      John     76
10    Kavya     89
11     Liam     91
12      Mia     84
13     Noah     73
14   Olivia     87


### 4. Filtering Data

In [18]:
# Students with score > 80
high_scores = df[df['Score'] > 80]
print("High Scorers:\n", high_scores)

High Scorers:
        Name  Age  Score
2   Charlie   23     90
3     David   24     85
4      Emma   20     88
6     Grace   22     95
8    Ishaan   21     82
10    Kavya   22     89
11     Liam   23     91
12      Mia   20     84
14   Olivia   21     87


### 5. Sorting Data

In [20]:
# Sort by Score (descending)
print(df.sort_values(by='Score', ascending=False))

       Name  Age  Score
6     Grace   22     95
11     Liam   23     91
2   Charlie   23     90
10    Kavya   22     89
4      Emma   20     88
14   Olivia   21     87
3     David   24     85
12      Mia   20     84
8    Ishaan   21     82
0     Alice   21     80
7    Hannah   23     78
9      John   24     76
1       Bob   22     75
13     Noah   25     73
5     Frank   25     70


### 6. Adding New Column

In [21]:
df['Pass'] = df['Score'] > 75
print(df)

       Name  Age  Score   Pass
0     Alice   21     80   True
1       Bob   22     75  False
2   Charlie   23     90   True
3     David   24     85   True
4      Emma   20     88   True
5     Frank   25     70  False
6     Grace   22     95   True
7    Hannah   23     78   True
8    Ishaan   21     82   True
9      John   24     76   True
10    Kavya   22     89   True
11     Liam   23     91   True
12      Mia   20     84   True
13     Noah   25     73  False
14   Olivia   21     87   True


### 7. Updating Data

In [23]:
 df.loc[0, 'Score'] = 85   # Change value at location of Column
 df #here Score od Alice change to 85

       Name  Age  Score   Pass
0     Alice   21     85   True
1       Bob   22     75  False
2   Charlie   23     90   True
3     David   24     85   True
4      Emma   20     88   True
5     Frank   25     70  False
6     Grace   22     95   True
7    Hannah   23     78   True
8    Ishaan   21     82   True
9      John   24     76   True
10    Kavya   22     89   True
11     Liam   23     91   True
12      Mia   20     84   True
13     Noah   25     73  False
14   Olivia   21     87   True


### 8. Handling Missing Values

In [24]:
print(df.isnull().sum())   # Check missing values

df.fillna(0, inplace=True)   # Replace missing with 0

Name     0
Age      0
Score    0
Pass     0
dtype: int64

       Name  Age  Score   Pass
0     Alice   21     85   True
1       Bob   22     75  False
2   Charlie   23     90   True
3     David   24     85   True
4      Emma   20     88   True
5     Frank   25     70  False
6     Grace   22     95   True
7    Hannah   23     78   True
8    Ishaan   21     82   True
9      John   24     76   True
10    Kavya   22     89   True
11     Liam   23     91   True
12      Mia   20     84   True
13     Noah   25     73  False
14   Olivia   21     87   True


### 9. Grouping Data

In [25]:
# Example: group by Age
grouped = df.groupby('Age')['Score'].mean()
print(grouped)

Age
20    86.000000
21    84.666667
22    86.333333
23    86.333333
24    80.500000
25    71.500000
Name: Score, dtype: float64


### 10. Unique Values

In [ ]:
print(df['Age'].unique())
print(df['Age'].nunique())


### 11. Saving Data

In [26]:
df.to_csv("updated_data.csv", index=False)