In [18]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

## Load Data

In [19]:
df = pd.read_csv("../data/salary_data.csv")

In [20]:
print("🔍 Original Data:\n", df.head()) #first 5 values

🔍 Original Data:
     Age    Salary
0  22.0   50000.0
1  45.0  120000.0
2  30.0   80000.0
3   NaN   75000.0
4  35.0       NaN

In [21]:
df.shape #Shape(rows,Columns)

(25, 2)

## Checking For Missing values

In [22]:
df.isnull().sum()

Age       2
Salary    4
dtype: int64

## Handle Missing Values

In [23]:
# Fill Age with mean
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

          Age    Salary
0   22.000000   50000.0
1   45.000000  120000.0
2   30.000000   80000.0
3   32.869565   75000.0
4   35.000000       NaN
5   40.000000  110000.0
6   26.000000   68000.0
7   32.000000       NaN
8   29.000000   72000.0
9   32.869565  105000.0
10  38.000000   99000.0
11  27.000000   70000.0
12  33.000000   88000.0
13  36.000000       NaN
14  31.000000   82000.0
15  24.000000   60000.0
16  42.000000  115000.0
17  39.000000  102000.0
18  34.000000   91000.0
19  37.000000   96000.0
20  23.000000   55000.0
21  44.000000       NaN
22  25.000000   65000.0
23  43.000000  112000.0
24  21.000000   48000.0

In [24]:
df['Age'] = df['Age'].round(0).astype(int) # Round of the Age
df

    Age    Salary
0    22   50000.0
1    45  120000.0
2    30   80000.0
3    33   75000.0
4    35       NaN
5    40  110000.0
6    26   68000.0
7    32       NaN
8    29   72000.0
9    33  105000.0
10   38   99000.0
11   27   70000.0
12   33   88000.0
13   36       NaN
14   31   82000.0
15   24   60000.0
16   42  115000.0
17   39  102000.0
18   34   91000.0
19   37   96000.0
20   23   55000.0
21   44       NaN
22   25   65000.0
23   43  112000.0
24   21   48000.0

In [25]:
# Fill Salary with median (better for large values)
df['Salary'] = df['Salary'].fillna(df['Salary'].median())
df

    Age    Salary
0    22   50000.0
1    45  120000.0
2    30   80000.0
3    33   75000.0
4    35   82000.0
5    40  110000.0
6    26   68000.0
7    32   82000.0
8    29   72000.0
9    33  105000.0
10   38   99000.0
11   27   70000.0
12   33   88000.0
13   36   82000.0
14   31   82000.0
15   24   60000.0
16   42  115000.0
17   39  102000.0
18   34   91000.0
19   37   96000.0
20   23   55000.0
21   44   82000.0
22   25   65000.0
23   43  112000.0
24   21   48000.0

In [26]:
#Remove duplicates
df = df.drop_duplicates()
df

    Age    Salary
0    22   50000.0
1    45  120000.0
2    30   80000.0
3    33   75000.0
4    35   82000.0
5    40  110000.0
6    26   68000.0
7    32   82000.0
8    29   72000.0
9    33  105000.0
10   38   99000.0
11   27   70000.0
12   33   88000.0
13   36   82000.0
14   31   82000.0
15   24   60000.0
16   42  115000.0
17   39  102000.0
18   34   91000.0
19   37   96000.0
20   23   55000.0
21   44   82000.0
22   25   65000.0
23   43  112000.0
24   21   48000.0

In [27]:
df.shape # No Duplicates

(25, 2)

##  Statistical Summary

In [28]:
df.describe()

             Age         Salary
count  25.000000      25.000000
mean   32.880000   83640.000000
std     7.102347   20264.665471
min    21.000000   48000.000000
25%    27.000000   70000.000000
50%    33.000000   82000.000000
75%    38.000000   99000.000000
max    45.000000  120000.000000

###  Feature Scaling & Normalization

In [29]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)

In [30]:
scaled_df = pd.DataFrame(scaled_data, columns=['Age', 'Salary'])

In [31]:
scaled_data

array([[0.04166667, 0.02777778],
       [1.        , 1.        ],
       [0.375     , 0.44444444],
       [0.5       , 0.375     ],
       [0.58333333, 0.47222222],
       [0.79166667, 0.86111111],
       [0.20833333, 0.27777778],
       [0.45833333, 0.47222222],
       [0.33333333, 0.33333333],
       [0.5       , 0.79166667],
       [0.70833333, 0.70833333],
       [0.25      , 0.30555556],
       [0.5       , 0.55555556],
       [0.625     , 0.47222222],
       [0.41666667, 0.47222222],
       [0.125     , 0.16666667],
       [0.875     , 0.93055556],
       [0.75      , 0.75      ],
       [0.54166667, 0.59722222],
       [0.66666667, 0.66666667],
       [0.08333333, 0.09722222],
       [0.95833333, 0.47222222],
       [0.16666667, 0.23611111],
       [0.91666667, 0.88888889],
       [0.        , 0.        ]])

In [33]:
import os

os.makedirs("outputs", exist_ok=True)

In [34]:
# Save files tto outputs folder
df.to_csv("outputs/cleaned_data.csv", index=False)
scaled_df.to_csv("outputs/scaled_data.csv", index=False)

## What I Undersatnd ...

* Scaling converts different values (like Age = 22, Salary = 100000) into a common range (0 to 1) so they can be compared properly.
* Without scaling, large values (like Salary) dominate small values (like Age).
* Scaling ensures every feature gets equal importance.